/**
 * Communes by wilaya (58 official wilayas).
 * Generated from French Wikipedia:
 * https://fr.wikipedia.org/wiki/Liste_des_communes_d'Algérie
 *
 * Re-run: node scripts/fetch-algeria-communes.js
 */

export const ALGERIA_COMMUNES: Record<string, string[]> = {
  "Adrar": [
    "Adrar",
    "Akabli",
    "Aoulef",
    "Bouda",
    "Fenoughil",
    "inzghmir",
    "Ouled Ahmed Tammi",
    "Reggane",
    "Sali",
    "Sebaa",
    "Tamantit",
    "Tamekten",
    "Tamest",
    "Tit",
    "Tsabit",
    "Zaouiet Kounta"
  ],
  "Chlef": [
    "Abou El Hassan",
    "Aïn Merane",
    "Bénairia",
    "Beni Bouateb",
    "Beni Haoua",
    "Beni Rached",
    "Boukadir",
    "Bouzeghaia",
    "Breira",
    "Chettia",
    "Chlef",
    "Dahra",
    "El Hadjadj",
    "El Karimia",
    "El Marsa",
    "Harchoun",
    "Harenfa",
    "Labiod Medjadja",
    "Moussadek",
    "ONS",
    "Oued Fodda",
    "Oued Goussine",
    "Oued Sly",
    "Ouled Abbes",
    "Ouled Ben Abdelkader",
    "Ouled Fares",
    "Oum Drou",
    "Sendjas",
    "Sidi Abderrahmane",
    "Sidi Akkacha",
    "Sobha",
    "Tadjena",
    "Talassa",
    "Taougrite",
    "Ténès",
    "Zeboudja"
  ],
  "Laghouat": [
    "Aflou",
    "Aïn Madhi",
    "Aïn Sidi Ali",
    "Beidha",
    "Bennasser Benchohra",
    "Brida",
    "El Assafia",
    "El Ghicha",
    "El Houaita",
    "Gueltat Sidi Saad",
    "Hadj Mechri",
    "Hassi Delaa",
    "Hassi R'Mel",
    "Kheneg",
    "Ksar El Hirane",
    "Laghouat",
    "Oued M'Zi",
    "Oued Morra",
    "Sebgag",
    "Sidi Bouzid",
    "Sidi Makhlouf",
    "Tadjemout",
    "Tadjrouna",
    "Taouiala"
  ],
  "Oum El Bouaghi": [
    "Aïn Babouche",
    "Aïn Beïda",
    "Aïn Diss",
    "Aïn Fakroun",
    "Aïn Kercha",
    "Aïn M'lila",
    "Aïn Zitoun",
    "Behir Chergui",
    "Berriche",
    "Bir Chouhada",
    "Dhalaa",
    "El Amiria",
    "El Belala",
    "El Djazia",
    "El Fedjoudj Boughrara Saoudi",
    "El Harmilia",
    "Fkirina",
    "Hanchir Toumghani",
    "Ksar Sbahi",
    "Meskiana",
    "Oued Nini",
    "Ouled Gacem",
    "Ouled Hamla",
    "Ouled Zouaï",
    "Oum el Bouaghi",
    "Rahia",
    "Sigus",
    "Souk Naamane",
    "Zorg"
  ],
  "Batna": [
    "Abdelkader Azil",
    "Aïn Djasser",
    "Aïn Touta",
    "Aïn Yagout",
    "Arris",
    "Barika",
    "Batna",
    "Ben Foudhala El Hakania",
    "Bitam",
    "Boulhilat",
    "Boumagueur",
    "Boumia",
    "Bouzina",
    "Chemora",
    "Chir",
    "Djerma",
    "Djezar",
    "El Hassi",
    "El Madher",
    "Fesdis",
    "Foum Toub",
    "Ghassira",
    "Gosbat",
    "Guigba",
    "Hidoussa",
    "Ichmoul",
    "Inoughissen",
    "Kimmel",
    "Ksar Bellezma",
    "Larbaâ",
    "Lazrou",
    "Lemsane",
    "M'doukel",
    "Maafa",
    "Menaa",
    "Merouana",
    "N'Gaous",
    "ONS",
    "Oued Chaaba",
    "Oued El Ma",
    "Oued Taga",
    "Ouled Ammar",
    "Ouled Aouf",
    "Ouled Fadel",
    "Ouled Sellam",
    "Ouled Si Slimane",
    "Ouyoun El Assafir",
    "Rahbat",
    "Ras El Aioun",
    "Sefiane",
    "Seggana",
    "Seriana",
    "T'Kout",
    "Talkhamt",
    "Taxlent",
    "Tazoult",
    "Teniet El Abed",
    "Tighanimine",
    "Tigherghar",
    "Tilatou",
    "Timgad",
    "Zanat El Beida"
  ],
  "Bejaia": [
    "Adekar",
    "Aït Maouche",
    "Aït Mellikeche",
    "Aït-R'zine",
    "Aït-Smail",
    "Akbou",
    "Akfadou",
    "Amalou",
    "Amizour",
    "Aokas",
    "Barbacha",
    "Béjaïa",
    "Beni Djellil",
    "Beni Ksila",
    "Boudjellil",
    "Bouhamza",
    "Boukhelifa",
    "Chellata",
    "Chemini",
    "Darguina",
    "Draâ El-Kaïd",
    "El Kseur",
    "Fenaïa Ilmaten",
    "Ferraoun",
    "Ighil Ali",
    "Ighram",
    "Kendira",
    "Kherrata",
    "Leflaye",
    "M'cisna",
    "Melbou",
    "Oued Ghir",
    "Ouzellaguen",
    "Seddouk",
    "Semaoun",
    "Sidi-Aïch",
    "Sidi-Ayad",
    "Souk El Ténine",
    "Souk-Oufella",
    "Tala Hamza",
    "Tamokra",
    "Tamridjet",
    "Taourirt Ighil",
    "Taskriout",
    "Tazmalt",
    "Tibane",
    "Tichy",
    "Tifra",
    "Timezrit",
    "Tinabdher",
    "Tizi N'Berber",
    "Toudja"
  ],
  "Biskra": [
    "Aïn Naga",
    "Biskra",
    "Bordj Ben Azzouz",
    "Bouchagroune",
    "Chetma",
    "El Feidh",
    "El Ghrous",
    "El Hadjeb",
    "El Haouch",
    "El Mizaraa",
    "Foughala",
    "Khenguet Sidi Nadji",
    "Lichana",
    "Lioua",
    "M'Chouneche",
    "M'Lili",
    "Mekhadma",
    "Oumache",
    "Ourlal",
    "Sidi Okba",
    "Tolga",
    "Zeribet El Oued"
  ],
  "Bechar": [
    "Abadla",
    "Béchar",
    "Beni Ounif",
    "Boukais",
    "Erg Ferradj",
    "Kenadsa",
    "Lahmar",
    "Mechraa Houari Boumedienne",
    "Meridja",
    "Mougheul",
    "Taghit"
  ],
  "Blida": [
    "Aïn Romana",
    "Beni Mered",
    "Beni Tamou",
    "Benkhelil",
    "Blida",
    "Bouarfa",
    "Boufarik",
    "Bougara",
    "Bouinan",
    "Chebli",
    "Chiffa",
    "Chréa",
    "Djebabra",
    "El Affroun",
    "Guerouaou",
    "Hammam Melouane",
    "Larbaa",
    "Meftah",
    "Mouzaia",
    "Oued Alleug",
    "Oued Djer",
    "Ouled Slama",
    "Ouled Yaïch",
    "Souhane",
    "Soumaa"
  ],
  "Bouira": [
    "Aghbalou",
    "Ahl El Ksar",
    "Aïn Bessem",
    "Aïn El Hadjar",
    "Aïn El Turc",
    "Aïn Laloui",
    "Aït Laziz",
    "Aomar",
    "Ath Mansour",
    "Bechloul",
    "Bir Ghbalou",
    "Bordj Okhriss",
    "Bouderbala",
    "Bouira",
    "Boukram",
    "Chorfa",
    "Dechmia",
    "Dirrah",
    "Djebahia",
    "El Adjiba",
    "El Asnam",
    "El Hachimia",
    "El Hakimia",
    "El Khabouzia",
    "El Mokrani",
    "Guerrouma",
    "Hadjera Zerga",
    "Haizer",
    "Hanif",
    "Kadiria",
    "Lakhdaria",
    "M'Chedallah",
    "Maala",
    "Maamora",
    "Mezdour",
    "Oued El Berdi",
    "Ouled Rached",
    "Raouraoua",
    "Ridane",
    "Saharidj",
    "Souk El Khemis",
    "Sour El Ghouzlane",
    "Taghzout",
    "Taguedit",
    "Zbarbar"
  ],
  "Tamanrasset": [
    "Abalessa",
    "Ain Amguel",
    "Idles",
    "ONS",
    "Tamanrasset",
    "Tazrouk"
  ],
  "Tebessa": [
    "Aïn Zerga",
    "Bedjene",
    "Bekkaria",
    "Bir Dheb",
    "Bir el-Ater",
    "Bir Mokkadem",
    "Boukhadra",
    "Boulhaf Dir",
    "Cheria",
    "El Aouinet",
    "El Houidjbet",
    "El Kouif",
    "El Ma Labiodh",
    "El Meridj",
    "El Mezeraa",
    "El Ogla",
    "Ferkane",
    "Guorriguer",
    "Hammamet",
    "Morsott",
    "Negrine",
    "Ogla Melha",
    "Ouenza",
    "Oum Ali",
    "Safsaf El Ouesra",
    "Stah Guentis",
    "Tébessa",
    "Tlidjene"
  ],
  "Tlemcen": [
    "Aïn Fetah",
    "Aïn Fezza",
    "Aïn Ghoraba",
    "Aïn Kebira",
    "Aïn Nehala",
    "Aïn Tallout",
    "Aïn Youcef",
    "Amieur",
    "Azails",
    "Bab El Assa",
    "Beni Bahdel",
    "Beni Boussaid",
    "Beni Khellad",
    "Beni Mester",
    "Beni Ouarsous",
    "Beni Semiel",
    "Beni Snous",
    "Bensekrane",
    "Bouhlou",
    "Chetouane",
    "Dar Yaghmouracene",
    "Djebala",
    "El Aricha",
    "El Bouihi",
    "El Fehoul",
    "El Gor",
    "Fellaoucene",
    "Ghazaouet",
    "Hammam Boughrara",
    "Hennaya",
    "Honaïne",
    "Maghnia",
    "Mansourah",
    "Marsa Ben M'Hidi",
    "MSirda Fouaga",
    "Nedroma",
    "Oued Lakhdar",
    "Ouled Mimoun",
    "Ouled Riyah",
    "Remchi",
    "Sabra",
    "Sebaa Chioukh",
    "Sebdou",
    "Sidi Abdelli",
    "Sidi Djillali",
    "Sidi Medjahed",
    "Souahlia",
    "Souani",
    "Souk Tlata",
    "Terny Beni Hdiel",
    "Tienet",
    "Tlemcen",
    "Zenata"
  ],
  "Tiaret": [
    "Aïn Bouchekif",
    "Aïn Deheb",
    "Aïn Dzarit",
    "Aïn El Hadid",
    "Aïn Kermes",
    "Bougara",
    "Chehaima",
    "Dahmouni",
    "Djebilet Rosfa",
    "Djillali Ben Amar",
    "Faidja",
    "Frenda",
    "Guertoufa",
    "Madna",
    "Mahdia",
    "Mechraa Safa",
    "Medrissa",
    "Medroussa",
    "Meghila",
    "Mellakou",
    "Nadorah",
    "Naima",
    "Oued Lilli",
    "Rahouia",
    "Sebaïne",
    "Sebt",
    "Si Abdelghani",
    "Sidi Abderahmane",
    "Sidi Ali Mellal",
    "Sidi Bakhti",
    "Sidi Hosni",
    "Sougueur",
    "Tagdemt",
    "Takhemaret",
    "Tiaret",
    "Tidda",
    "Tousnina"
  ],
  "Tizi Ouzou": [
    "Abi Youcef",
    "Aghribs",
    "Agouni Gueghrane",
    "Ain El Hammam",
    "Aïn Zaouia",
    "Aït Aggouacha",
    "Aït Aïssa Mimoun",
    "Aït Aïssi",
    "Aït Bouaddou",
    "Aït Boumahdi",
    "Aït Chafâa",
    "Aït Khellili",
    "Aït Mahmoud",
    "Aït Ouacif",
    "Aït Oumalou",
    "Aït Toudert",
    "Aït Yahia",
    "Aït Yahia Moussa",
    "Aït Yenni",
    "Aït Zmenzer",
    "Akbil",
    "Akerrou",
    "Assi Youcef",
    "Ath Zikki",
    "Azazga",
    "Azeffoun",
    "Beni Douala",
    "Boghni",
    "Boudjima",
    "Bounouh",
    "Bouzeguène",
    "Draâ Ben Khedda",
    "Draâ El Mizan",
    "Freha",
    "Frikat",
    "Iboudraren",
    "Idjeur",
    "Iferhounène",
    "Ifigha",
    "Iflissen",
    "Illilten",
    "Illoula Oumalou",
    "Imkiren",
    "Imsouhel",
    "Irdjen",
    "Larbaâ Nath Irathen",
    "Mâatkas",
    "Makouda",
    "Mechtras",
    "Mekla",
    "Mizrana",
    "Ouadhia",
    "Ouaguenoun",
    "Sidi Namane",
    "Souamaâ",
    "Souk El Thenine",
    "Tadmaït",
    "Tigzirt",
    "Timizart",
    "Tirmitine",
    "Tizi Gheniff",
    "Tizi N'Tleta",
    "Tizi Ouzou",
    "Tizi Rached",
    "Yakouren",
    "Yatafen",
    "Zekri"
  ],
  "Alger": [
    "Aïn Benian",
    "Aïn Taya",
    "Alger-Centre",
    "Bab El Oued",
    "Bab Ezzouar",
    "Baba Hassen",
    "Bachdjerrah",
    "Baraki",
    "Belouizdad",
    "Ben Aknoun",
    "Beni Messous",
    "Bir Mourad Raïs",
    "Birkhadem",
    "Birtouta",
    "Bologhine",
    "Bordj El Bahri",
    "Bordj El Kiffan",
    "Bourouba",
    "Bouzareah",
    "Casbah",
    "Cheraga",
    "Dar El Beïda",
    "Dely Ibrahim",
    "Djasr Kasentina",
    "Douera",
    "Draria",
    "El Achour",
    "El Biar",
    "El Harrach",
    "El Madania",
    "El Magharia",
    "El Marsa",
    "El Mouradia",
    "H'raoua",
    "Hammamet",
    "Hussein Dey",
    "Hydra",
    "Khraicia",
    "Kouba",
    "Les Eucalyptus",
    "Mahelma",
    "Mohammadia",
    "Oued Koriche",
    "Oued Smar",
    "Ouled Chebel",
    "Ouled Fayet",
    "Rahmania",
    "Raïs Hamidou",
    "Reghaïa",
    "Rouïba",
    "Saoula",
    "Sidi M'Hamed",
    "Sidi Moussa",
    "Souidania",
    "Staoueli",
    "Tessala El Merdja",
    "Zeralda"
  ],
  "Djelfa": [
    "Aïn Chouhada",
    "Aïn El Ibel",
    "Aïn Maabed",
    "Beni Yagoub",
    "Charef",
    "Dar Chioukh",
    "Djelfa",
    "Douis",
    "El Guedid",
    "El Idrissia",
    "Hassi Bahbah",
    "Hassi El Euch",
    "M'Liliha",
    "Moudjebara",
    "Sidi Baizid",
    "Tadmit",
    "Zaafrane"
  ],
  "Jijel": [
    "Bordj Tahar",
    "Boucif Ouled Askeur",
    "Boudriaa Ben Yadjis",
    "Bouraoui Belhadef",
    "Chahna",
    "Chekfa",
    "Djemaa Beni Habibi",
    "Djimla",
    "El Ancer",
    "El Aouana",
    "El Kennar Nouchfi",
    "El Milia",
    "Emir Abdelkader",
    "Eraguene",
    "Ghebala",
    "Jijel",
    "Kaous",
    "Kheïri Oued Adjoul",
    "Ouadjana",
    "Ouled Rabah",
    "Ouled Yahia Khedrouche",
    "Selma Benziada",
    "Settara",
    "Sidi Abdelaziz",
    "Sidi Maarouf",
    "Taher",
    "Texenna",
    "Ziama Mansouriah"
  ],
  "Sétif": [
    "Aïn Abessa",
    "Aïn Arnat",
    "Aïn Azel",
    "Aïn El Kebira",
    "Aïn Lahdjar",
    "Aïn Legradj",
    "Aïn Oulmene",
    "Aïn Roua",
    "Aïn Sebt",
    "Aït Naoual Mezada",
    "Aït Tizi",
    "Amoucha",
    "Babor",
    "Bazer Sakhra",
    "Beidha Bordj",
    "Belaa",
    "Beni Aziz",
    "Beni Chebana",
    "Beni Fouda",
    "Beni Hocine",
    "Beni Mouhli",
    "Beni Ouartilene",
    "Bir El Arch",
    "Bir Haddada",
    "Bouandas",
    "Bougaa",
    "Bousselam",
    "Boutaleb",
    "Dehamcha",
    "Djemila",
    "Draa Kebila",
    "El Eulma",
    "El Ouldja",
    "El Ouricia",
    "Guellal",
    "Guelta Zerka",
    "Guenzet",
    "Guidjel",
    "Hamma",
    "Hammam Guergour",
    "Hammam Soukhna",
    "Harbil",
    "Ksar El Abtal",
    "Maaouia",
    "Maoklane",
    "Mezloug",
    "Oued El Barad",
    "Ouled Addouane",
    "Ouled Sabor",
    "Ouled Si Ahmed",
    "Ouled Tebben",
    "Rasfa",
    "Salah Bey",
    "Serdj El Ghoul",
    "Sétif",
    "Tachouda",
    "Talaifacene",
    "Taya",
    "Tella",
    "Tizi N'Bechar"
  ],
  "Saida": [
    "Aïn El Hadjar",
    "Aïn Sekhouna",
    "Aïn Soltane",
    "Doui Thabet",
    "El Hassasna",
    "Hounet",
    "Maamora",
    "Moulay Larbi",
    "Ouled Brahim",
    "Ouled Khaled",
    "Saïda",
    "Sidi Ahmed",
    "Sidi Amar",
    "Sidi Boubekeur",
    "Tircine",
    "Youb"
  ],
  "Skikda": [
    "Aïn Bouziane",
    "Aïn Charchar",
    "Aïn Kechra",
    "Aïn Zouit",
    "Azzaba",
    "Bekkouche Lakhdar",
    "Ben Azzouz",
    "Beni Bechir",
    "Beni Oulbane",
    "Beni Zid",
    "Bin El Ouiden",
    "Bouchtata",
    "Cheraia",
    "Collo",
    "Djendel Saadi Mohamed",
    "El Ghedir",
    "El Hadaiek",
    "El Harrouch",
    "El Marsa",
    "Emdjez Edchich",
    "Es Sebt",
    "Filfila",
    "Hamadi Krouma",
    "Kanoua",
    "Kerkera",
    "Kheneg Mayoum",
    "Oued Zehour",
    "Ouldja Boulballout",
    "Ouled Attia",
    "Ouled Hbaba",
    "Oum Toub",
    "Ramdane Djamel",
    "Salah Bouchaour",
    "Sidi Mezghiche",
    "Skikda",
    "Tamalous",
    "Zerdaza",
    "Zitouna"
  ],
  "Sidi Bel Abbès": [
    "Aïn Adden",
    "Aïn El Berd",
    "Aïn Kada",
    "Aïn Thrid",
    "Aïn Tindamine",
    "Amarnas",
    "Badredine El Mokrani",
    "Belarbi",
    "Ben Badis",
    "Benachiba Chelia",
    "Bir El Hammam",
    "Boudjebaa El Bordj",
    "Boukhanafis",
    "Chettouane Belaila",
    "Code postal",
    "Dhaya",
    "El Haçaiba",
    "Hassi Dahou",
    "Hassi Zehana",
    "Lamtar",
    "M'Cid",
    "Makedra",
    "Marhoum",
    "Merine",
    "Mezaourou",
    "Mostefa Ben Brahim",
    "Moulay Slissen",
    "Oued Sebaa",
    "Oued Sefioun",
    "Oued Taourira",
    "Ras El Ma",
    "Redjem Demouche",
    "Sehala Thaoura",
    "Sfisef",
    "Sidi Ali Benyoub",
    "Sidi Ali Boussidi",
    "Sidi Bel Abbes",
    "Sidi Brahim",
    "Sidi Chaib",
    "Sidi Daho des Zairs",
    "Sidi Hamadouche",
    "Sidi Khaled",
    "Sidi Lahcene",
    "Sidi Yacoub",
    "Tabia",
    "Tafissour",
    "Taoudmout",
    "Teghalimet",
    "Telagh",
    "Tenira",
    "Tessala",
    "Tilmouni",
    "Zerouala"
  ],
  "Annaba": [
    "Aïn Berda",
    "Annaba",
    "Berrahal",
    "Chetaïbi",
    "Cheurfa",
    "El Bouni",
    "El Hadjar",
    "Eulma",
    "Oued El Aneb",
    "Seraïdi",
    "Sidi Amar",
    "Treat"
  ],
  "Guelma": [
    "Aïn Ben Beida",
    "Aïn Larbi",
    "Aïn Makhlouf",
    "Aïn Reggada",
    "Aïn Sandel",
    "Belkheir",
    "Ben Djerrah",
    "Beni Mezline",
    "Bordj Sabath",
    "Bouati Mahmoud",
    "Bouchegouf",
    "Bouhachana",
    "Bouhamdane",
    "Boumahra Ahmed",
    "Dahouara",
    "Djeballah Khemissi",
    "El Fedjoudj",
    "Guellat Bou Sbaa",
    "Guelma",
    "Hammam Debagh",
    "Hammam N'Bail",
    "Héliopolis",
    "Houari Boumédiène",
    "Khezarra",
    "Medjez Amar",
    "Medjez Sfa",
    "Nechmaya",
    "Oued Cheham",
    "Oued Fragha",
    "Oued Zenati",
    "Ras El Agba",
    "Roknia",
    "Sellaoua Announa",
    "Tamlouka"
  ],
  "Constantine": [
    "Aïn Abid",
    "Aïn Smara",
    "Beni Hamiden",
    "Constantine",
    "Didouche Mourad",
    "El Khroub",
    "Hamma Bouziane",
    "Ibn Badis",
    "Ibn Ziad",
    "Messaoud Boudjriou",
    "Ouled Rahmoune",
    "Zighoud Youcef"
  ],
  "Medea": [
    "Aissaouia",
    "Baata",
    "Benchicao",
    "Beni Slimane",
    "Berrouaghia",
    "Bir Ben Laabed",
    "Bouaichoune",
    "Bouchrahil",
    "Bouskene",
    "Deux Bassins",
    "Djouab",
    "Draa Essamar",
    "El Azizia",
    "El Guelb El Kebir",
    "El Hamdania",
    "El Omaria",
    "Hannacha",
    "Khams Djouamaa",
    "Médéa",
    "Meghraoua",
    "Mezerana",
    "Mihoub",
    "Moudjbar",
    "Ouamri",
    "Oued Harbil",
    "Ouled Bouachra",
    "Ouled Brahim",
    "Ouled Deide",
    "Ouzera",
    "Rebaia",
    "Sedraia",
    "Seghouane",
    "Si Mahdjoub",
    "Sidi Errabia",
    "Sidi Naamane",
    "Sidi Zahar",
    "Sidi Ziane",
    "Souagui",
    "Tablat",
    "Tamesguida",
    "Tizi Mahdi",
    "Tlatet Eddouar",
    "Zoubiria"
  ],
  "Mostaganem": [
    "Abdelmalek Ramdane",
    "Achaacha",
    "Aïn Boudinar",
    "Aïn Nouissy",
    "Aïn Sidi Cherif",
    "Aïn Tedles",
    "Blad Touahria",
    "Bouguirat",
    "El Hassiane",
    "Fornaka",
    "Hadjadj",
    "Hassi Mameche",
    "Khadra",
    "Kheireddine",
    "Mansourah",
    "Mazagran",
    "Mesra",
    "Mostaganem",
    "Nekmaria",
    "Oued El Kheir",
    "Ouled Boughalem",
    "Ouled Maallah",
    "Safsaf",
    "Sayada",
    "Sidi Ali",
    "Sidi Belattar",
    "Sidi Lakhdar",
    "Sirat",
    "Souaflia",
    "Sour",
    "Stidia",
    "Tazgait"
  ],
  "M'Sila": [
    "Aïn El Hadjel",
    "Aïn Khadra",
    "Belaiba",
    "Beni Ilmane",
    "Berhoum",
    "Bouti Sayah",
    "Chellal",
    "Dehahna",
    "Hammam Dhalaa",
    "Khettouti Sed El Djir",
    "M'Sila",
    "M'Tarfa",
    "Maadid",
    "Maarif",
    "Magra",
    "Ouanougha",
    "Ouled Addi Guebala",
    "Ouled Atia",
    "Ouled Derradj",
    "Ouled Madhi",
    "Ouled Mansour",
    "Sidi Aïssa",
    "Sidi Hadjeres",
    "Souamaa",
    "Tarmount"
  ],
  "Mascara": [
    "Aïn Fares",
    "Aïn Fekan",
    "Aïn Ferah",
    "Aïn Fras",
    "Alaïmia",
    "Aouf",
    "Beniane",
    "Bou Hanifia",
    "Bou Henni",
    "Chorfa",
    "El Bordj",
    "El Gaada",
    "El Ghomri",
    "El Guettana",
    "El Keurt",
    "El Menaouer",
    "Ferraguig",
    "Froha",
    "Gharrous",
    "Ghriss",
    "Guerdjoum",
    "Hachem",
    "Hacine",
    "Khalouia",
    "Makdha",
    "Mamounia",
    "Maoussa",
    "Mascara",
    "Matemore",
    "Mocta Douz",
    "Mohammadia",
    "Nesmoth",
    "Oggaz",
    "Oued El Abtal",
    "Oued Taria",
    "Ras El Aïn Amirouche",
    "Sedjerara",
    "Sehailia",
    "Sidi Abdeldjebar",
    "Sidi Abdelmoumen",
    "Sidi Boussaid",
    "Sidi Kada",
    "Sig",
    "Tighennif",
    "Tizi",
    "Zahana",
    "Zelmata"
  ],
  "Ouargla": [
    "Aïn Beida",
    "El Allia",
    "El Borma",
    "El Hadjira",
    "Hassi Ben Abdellah",
    "Hassi Messaoud",
    "N'Goussa",
    "Ouargla",
    "Rouissat",
    "Sidi Khouiled"
  ],
  "Oran": [
    "Aïn El Bia",
    "Aïn El Kerma",
    "Aïn El Turk",
    "Arzew",
    "Ben Freha",
    "Bethioua",
    "Bir El Djir",
    "Boufatis",
    "Bousfer",
    "Boutlelis",
    "El Ançor",
    "El Braya",
    "El Kerma",
    "Es Senia",
    "Gdyel",
    "Hassi Ben Okba",
    "Hassi Bounif",
    "Hassi Mefsoukh",
    "Marsat El Hadjadj",
    "Mers El Kébir",
    "Misserghin",
    "Oran",
    "Oued Tlelat",
    "Sidi Benyebka",
    "Sidi Chami",
    "Tafraoui"
  ],
  "El Bayadh": [
    "Aïn El Orak",
    "Arbaouat",
    "Boualem",
    "Bougtoub",
    "Boussemghoun",
    "Brezina",
    "Cheguig",
    "Chellala",
    "El Abiodh Sidi Cheikh",
    "El Bayadh",
    "El Bnoud",
    "El Kheiter",
    "El Mehara",
    "Ghassoul",
    "Kef El Ahmar",
    "Kraakda",
    "ONS",
    "Rogassa",
    "Sidi Ameur",
    "Sidi Slimane",
    "Sidi Tifour",
    "Stitten",
    "Tousmouline"
  ],
  "Illizi": [
    "Bordj Omar Driss",
    "Debdeb",
    "Illizi",
    "In Amenas"
  ],
  "Bordj Bou Arreridj": [
    "Aïn Taghrout",
    "Aïn Tesra",
    "Belimour",
    "Ben Daoud",
    "Bir Kasdali",
    "Bordj Bou Arreridj",
    "Bordj Ghedir",
    "Bordj Zemoura",
    "Colla",
    "Djaafra",
    "El Ach",
    "El Achir",
    "El Anseur",
    "El Hamadia",
    "El M'hir",
    "El Main",
    "Ghilassa",
    "Haraza",
    "Hasnaoua",
    "Khelil",
    "Ksour",
    "Mansoura",
    "Medjana",
    "Ouled Brahem",
    "Ouled Dahmane",
    "Ouled Sidi Brahim",
    "Rabta",
    "Ras El Oued",
    "Sidi Embarek",
    "Taglait",
    "Tassameurt",
    "Tefreg",
    "Teniet En Nasr",
    "Tixter"
  ],
  "Boumerdes": [
    "Afir",
    "Ammal",
    "Baghlia",
    "Ben Choud",
    "Beni Amrane",
    "Bordj Menaïel",
    "Boudouaou",
    "Boudouaou-El-Bahri",
    "Boumerdes",
    "Bouzegza Keddara",
    "Chabet el Ameur",
    "Corso",
    "Dellys",
    "Djinet",
    "El Kharrouba",
    "Hammedi",
    "Issers",
    "Khemis El-Khechna",
    "Larbatache",
    "Leghata",
    "Naciria",
    "Ouled Aïssa",
    "Ouled Hedadj",
    "Ouled Moussa",
    "Si Mustapha",
    "Sidi Daoud",
    "Souk El Had",
    "Taourga",
    "Thenia",
    "Tidjelabine",
    "Timezrit",
    "Zemmouri"
  ],
  "El Tarf": [
    "Aïn El Assel",
    "Aïn Kerma",
    "Asfour",
    "Ben Mehidi",
    "Berrihane",
    "Besbes",
    "Bougous",
    "Bouhadjar",
    "Bouteldja",
    "Chebaita Mokhtar",
    "Chefia",
    "Chihani",
    "Dréan",
    "Echatt",
    "El Aioun",
    "El Kala",
    "El Tarf",
    "Hammam Beni Salah",
    "Lac des Oiseaux",
    "Oued Zitoun",
    "Raml Souk",
    "Souarekh",
    "Zerizer",
    "Zitouna"
  ],
  "Tindouf": [
    "Oum el Assel",
    "Tindouf"
  ],
  "Tissemsilt": [
    "Ammari",
    "Beni Chaib",
    "Beni Lahcene",
    "Bordj Bou Naama",
    "Bordj El Emir Abdelkader",
    "Boucaid",
    "Khemisti",
    "Larbaa",
    "Lardjem",
    "Layoune",
    "Lazharia",
    "Maacem",
    "Melaab",
    "Ouled Bessem",
    "Sidi Abed",
    "Sidi Boutouchent",
    "Sidi Lantri",
    "Sidi Slimane",
    "Tamalaht",
    "Theniet El Had",
    "Tissemsilt",
    "Youssoufia"
  ],
  "El Oued": [
    "Bayadha",
    "Beni Guecha",
    "Debila",
    "Douar El Ma",
    "El Ogla",
    "El Oued",
    "Guemar",
    "Hamraia",
    "Hassani Abdelkrim",
    "Hassi Khalifa",
    "Kouinine",
    "Magrane",
    "Mih Ouansa",
    "Nakhla",
    "Oued El Alenda",
    "Ourmas",
    "Reguiba",
    "Robbah",
    "Sidi Aoun",
    "Taghzout",
    "Taleb Larbi",
    "Trifaoui"
  ],
  "Khenchela": [
    "Aïn Touila",
    "Babar",
    "Baghai",
    "Bouhmama",
    "Chechar",
    "Chelia",
    "Djellal",
    "El Hamma",
    "El Mahmal",
    "El Oueldja",
    "Ensigha",
    "Kaïs",
    "Khenchela",
    "Khirane",
    "M'Sara",
    "M'Toussa",
    "Ouled Rechache",
    "Remila",
    "Tamza",
    "Taouzient",
    "Yabous"
  ],
  "Souk Ahras": [
    "Aïn Soltane",
    "Aïn Zana",
    "Bir Bou Haouch",
    "Dréa",
    "Hanancha",
    "Heddada",
    "Khedara",
    "Khemissa",
    "M'daourouch",
    "Mechroha",
    "Merahna",
    "Oued Keberit",
    "Ouillen",
    "Ouled Driss",
    "Ouled Moumene",
    "Oum El Adhaim",
    "Ragouba",
    "Safel El Ouiden",
    "Sedrata",
    "Sidi Fredj",
    "Souk Ahras",
    "Taoura",
    "Terraguelt",
    "Tiffech",
    "Zaarouria",
    "Zouabi"
  ],
  "Tipaza": [
    "Aghbal",
    "Ahmar El Aïn",
    "Aïn Tagourait",
    "Attatba",
    "Beni Milleuk",
    "Bou Ismaïl",
    "Bouharoun",
    "Bourkika",
    "Chaiba",
    "Cherchell",
    "Damous",
    "Douaouda",
    "Fouka",
    "Gouraya",
    "Hadjeret Ennous",
    "Hadjout",
    "Khemisti",
    "Koléa",
    "Larhat",
    "Menaceur",
    "Merad",
    "Messelmoun",
    "Nador",
    "Sidi Amar",
    "Sidi Ghiles",
    "Sidi Rached",
    "Sidi Semiane",
    "Tipaza"
  ],
  "Mila": [
    "Ahmed Rachedi",
    "Aïn Beida Harriche",
    "Aïn Mellouk",
    "Aïn Tine",
    "Amira Arrès",
    "Benyahia Abderrahmane",
    "Bouhatem",
    "Chelghoum Laid",
    "Chigara",
    "Derradji Bousselah",
    "El Mechira",
    "Elayadi Barbes",
    "Ferdjioua",
    "Grarem Gouga",
    "Hamala",
    "Mila",
    "Minar Zarza",
    "Oued Athmania",
    "Oued Endja",
    "Oued Seguen",
    "Ouled Khalouf",
    "Rouached",
    "Sidi Khelifa",
    "Sidi Merouane",
    "Tadjenanet",
    "Tassadane Haddada",
    "Teleghma",
    "Terrai Bainen",
    "Tessala Lemtaï",
    "Tiberguent",
    "Yahia Beni Guecha",
    "Zeghaia"
  ],
  "Ain Defla": [
    "Aïn Benian",
    "Aïn Bouyahia",
    "Aïn Defla",
    "Aïn Lechiekh",
    "Aïn Soltane",
    "Aïn Torki",
    "Arib",
    "Bathia",
    "Belaas",
    "Ben Allal",
    "Bir Ould Khelifa",
    "Birbouche",
    "Bordj Emir Khaled",
    "Boumedfaa",
    "Bourached",
    "Djelida",
    "Djemaa Ouled Cheikh",
    "Djendel",
    "El Abadia",
    "El Amra",
    "El Attaf",
    "El Hassania",
    "El Maine",
    "Hammam Righa",
    "Hoceinia",
    "Khemis Miliana",
    "Mekhatria",
    "Miliana",
    "Oued Chorfa",
    "Oued Djemaa",
    "Rouina",
    "Sidi Lakhdar",
    "Tacheta Zougagha",
    "Tarik Ibn Ziad",
    "Tiberkanine",
    "Zeddine"
  ],
  "Naama": [
    "Aïn Ben Khelil",
    "Aïn Sefra",
    "Assela",
    "Djeniene Bourezg",
    "El Biod",
    "Kasdir",
    "Makman Ben Amer",
    "Mecheria",
    "Moghrar",
    "Naâma",
    "Sfissifa",
    "Tiout"
  ],
  "Ain Temouchent": [
    "Aghlal",
    "Aïn El Arbaa",
    "Aïn Kihal",
    "Aïn Témouchent",
    "Aïn Tolba",
    "Aoubellil",
    "Beni Saf",
    "Bouzedjar",
    "Chaabat El Leham",
    "Chentouf",
    "El Amria",
    "El Emir Abdelkader",
    "El Malah",
    "El Messaid",
    "Hammam Bouhadjar",
    "Hassasna",
    "Hassi El Ghella",
    "Oued Berkeche",
    "Oued Sabah",
    "Ouled Boudjemaa",
    "Ouled Kihal",
    "Oulhaça El Gheraba",
    "Sidi Ben Adda",
    "Sidi Boumedienne",
    "Sidi Ouriache",
    "Sidi Safi",
    "Tamzoura",
    "Terga"
  ],
  "Ghardaia": [
    "Berriane",
    "Bounoura",
    "Dhayet Bendhahoua",
    "El Atteuf",
    "El Guerrara",
    "Ghardaïa",
    "Mansoura",
    "Metlili",
    "Sebseb",
    "Zelfana"
  ],
  "Relizane": [
    "Aïn Rahma",
    "Aïn Tarek",
    "Ammi Moussa",
    "Belassel Bouzegza",
    "Bendaoud",
    "Beni Dergoun",
    "Beni Zentis",
    "Dar Ben Abdellah",
    "Djidioua",
    "El Guettar",
    "El Hamadna",
    "El Hassi",
    "El Matmar",
    "El Ouldja",
    "Had Echkalla",
    "Hamri",
    "Kalaa",
    "Lahlef",
    "Mazouna",
    "Mediouna",
    "Mendes",
    "Merdja Sidi Abed",
    "Ouarizane",
    "Oued El Djemaa",
    "Oued Essalem",
    "Oued Rhiou",
    "Ouled Aiche",
    "Ouled Sidi Mihoub",
    "Ramka",
    "Relizane",
    "Sidi Khettab",
    "Sidi Lazreg",
    "Sidi M'Hamed Ben Ali",
    "Sidi M'Hamed Benaouda",
    "Sidi Saada",
    "Souk El Had",
    "Yellel",
    "Zemmora"
  ],
  "Timimoun": [
    "Aougrout",
    "Charouine",
    "Deldoul",
    "Ksar Kaddour",
    "Metarfa",
    "Ouled Aïssa",
    "Ouled Saïd",
    "Talmine",
    "Timimoun",
    "Tinerkouk"
  ],
  "Bordj Badji Mokhtar": [
    "Bordj Badji Mokhtar",
    "Timiaouine"
  ],
  "Ouled Djellal": [
    "Besbes",
    "Doucen",
    "Ech Chaïba",
    "Ouled Djellal",
    "Ras El Miaad",
    "Sidi Khaled"
  ],
  "Béni Abbès": [
    "Béni Abbès",
    "Beni Ikhlef",
    "El Ouata",
    "Igli",
    "Kerzaz",
    "Ksabi",
    "Oulad khodeir",
    "Tabelbala",
    "Tamtert",
    "Timoudi"
  ],
  "In Salah": [
    "Foggaret Ezzaouia",
    "In Ghar",
    "In Salah"
  ],
  "In Guezzam": [
    "In Guezzam",
    "Tin Zaouatine"
  ],
  "Touggourt": [
    "Benaceur",
    "Blidet Amor",
    "El Allia",
    "El Hadjira",
    "M'Naguer",
    "Megarine",
    "Nezla",
    "Sidi Slimane",
    "Taibet",
    "Tebesbest",
    "Temacine",
    "Touggourt",
    "Zaouia El Abidia"
  ],
  "Djanet": [
    "Bordj El Haouas",
    "Djanet"
  ],
  "El Meghaier": [
    "Djamaa",
    "El M'Ghair",
    "Merara",
    "Oum Touyour",
    "Sidi Amrane",
    "Sidi Khellil",
    "Still",
    "Tendla"
  ],
  "El Menia": [
    "El Menia",
    "Hassi Fehal",
    "Hassi Gara"
  ]
}

/** Lookup communes for a wilaya name (supports common aliases). */
export function getCommunesForWilaya(wilaya: string): string[] {
  if (!wilaya) return []
  if (ALGERIA_COMMUNES[wilaya]?.length) return ALGERIA_COMMUNES[wilaya]

  const aliases: Record<string, string> = {
    Algiers: 'Alger',
    Béjaïa: 'Bejaia',
    Bejaia: 'Bejaia',
    Béchar: 'Bechar',
    Bechar: 'Bechar',
    Tébessa: 'Tebessa',
    Tebessa: 'Tebessa',
    Sétif: 'Sétif',
    Setif: 'Sétif',
    Saïda: 'Saida',
    Saida: 'Saida',
    Médéa: 'Medea',
    Medea: 'Medea',
    Boumerdès: 'Boumerdes',
    Boumerdes: 'Boumerdes',
    'Aïn Defla': 'Ain Defla',
    'Ain Defla': 'Ain Defla',
    'Aïn Témouchent': 'Ain Temouchent',
    'Ain Temouchent': 'Ain Temouchent',
    Ghardaïa: 'Ghardaia',
    Ghardaia: 'Ghardaia',
    "El M'Ghair": 'El Meghaier',
    'El Meghaier': 'El Meghaier',
    'El Meniaa': 'El Menia',
    'El Ménia': 'El Menia',
    'Bordj Bou Arréridj': 'Bordj Bou Arreridj',
  }

  const mapped = aliases[wilaya]
  if (mapped && ALGERIA_COMMUNES[mapped]?.length) return ALGERIA_COMMUNES[mapped]

  const lower = wilaya.toLowerCase()
  const hit = Object.keys(ALGERIA_COMMUNES).find((k) => k.toLowerCase() === lower)
  return hit ? ALGERIA_COMMUNES[hit] : []
}
